# Generated by Django 5.1.4 on 2025-03-19 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabc', '0012_alter_roleacesspermission_permission'),
        ('users', '0011_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='rabc.role'),
        ),
    ]
