# Generated by Django 5.1.4 on 2025-03-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='custome_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
