# Generated by Django 5.1.4 on 2025-03-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_remove_leadacess_lead_leadacess_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadacess',
            name='lead',
        ),
        migrations.AddField(
            model_name='leadacess',
            name='lead',
            field=models.ManyToManyField(to='leads.leads'),
        ),
    ]
