# Generated by Django 5.1.4 on 2025-04-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_leadacess_granted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('follow_up', 'Follow-up Scheduled'), ('negotiation', 'Negotiation'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=255)),
                ('custome_fields', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
