# Generated by Django 5.1.4 on 2025-04-01 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_webform'),
        ('users', '0012_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AddField(
            model_name='leads',
            name='form_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.webform'),
        ),
        migrations.AddField(
            model_name='leads',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_by', to='users.employee'),
        ),
        migrations.DeleteModel(
            name='LeadAcess',
        ),
    ]
