# Generated by Django 5.1.4 on 2025-04-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_leads_employee_leads_form_data_leads_granted_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='webform',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='webform',
            name='last_name',
        ),
    ]
