# Generated by Django 5.1.4 on 2025-04-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_rename_first_name_leads_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='id',
        ),
        migrations.RemoveField(
            model_name='webform',
            name='id',
        ),
        migrations.AddField(
            model_name='leads',
            name='lead_id',
            field=models.CharField(default=None, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='webform',
            name='web_id',
            field=models.CharField(default=None, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
