# Generated by Django 5.1.4 on 2025-04-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_remove_leads_id_remove_webform_id_leads_lead_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_id',
            field=models.CharField(blank=True, default=None, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='webform',
            name='web_id',
            field=models.CharField(blank=True, default=None, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
