# Generated by Django 5.1.4 on 2025-04-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_alter_leads_lead_id_alter_webform_web_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='last_name',
        ),
    ]
