# Generated by Django 5.1.4 on 2025-04-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_remove_leads_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_id',
            field=models.CharField(blank=True, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
