# Generated by Django 5.1.4 on 2025-04-03 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_alter_leads_form_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='form_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.webform'),
        ),
    ]
