# Generated by Django 5.1.8 on 2025-05-08 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_leadnotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadnotes',
            old_name='account',
            new_name='lead',
        ),
    ]
