# Generated by Django 5.1.8 on 2025-06-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_contact_is_primary_contact'),
        ('leads', '0023_account_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='account',
        ),
        migrations.AddField(
            model_name='deal',
            name='account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Customer.accounts'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
