# Generated by Django 5.1.8 on 2025-06-09 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_remove_deal_account_deal_account_id_delete_account'),
        ('users', '0012_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee'),
        ),
    ]
