# Generated by Django 5.1.8 on 2025-06-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_alter_deal_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(blank=True, choices=[('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_lost', 'Closed Lost'), ('closed_won', 'Closed Won'), ('discovery', 'Discovery')], max_length=100, null=True),
        ),
    ]
