# Generated by Django 5.1.8 on 2025-06-10 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_contact_is_primary_contact'),
        ('leads', '0026_alter_deal_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='account_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='Customer.accounts'),
        ),
    ]
