# Generated by Django 5.1.8 on 2025-06-17 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_deal_owner_alter_deal_created_by'),
        ('users', '0012_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deal_notes', to='users.employee')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.deal')),
            ],
        ),
    ]
