# Generated by Django 5.1.8 on 2025-06-18 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_dealnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealnotes',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.deal'),
        ),
    ]
