# Generated by Django 5.1.8 on 2025-06-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_leads_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='webform',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('referral', 'Referral'), ('other', 'Other')], default='website', max_length=50),
        ),
    ]
