# Generated by Django 5.1.8 on 2025-07-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_alter_deal_amount_alter_deal_priority_and_more'),
        ('users', '0012_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_by', to='users.employee'),
        ),
    ]
