# Generated by Django 5.1.8 on 2025-04-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('leads', '0020_alter_leads_form_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.leads'),
        ),
    ]
