# Generated by Django 5.1.8 on 2025-04-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect')], default='active', max_length=20),
        ),
    ]
