# Generated by Django 5.1.8 on 2025-04-27 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_accounts_address_accounts_notes_accounts_status'),
        ('leads', '0020_alter_leads_form_data'),
        ('users', '0012_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_acounts', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employee'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_acount', to='leads.leads'),
        ),
    ]
