# Generated by Django 5.1.8 on 2025-04-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_alter_contact_assigned_by_alter_contact_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='custome_fields',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
