# Generated by Django 5.1.8 on 2025-06-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_remove_contact_lead_contact_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='Customer.accounts'),
        ),
    ]
