# Generated by Django 5.1.8 on 2025-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_contact_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
