# Generated by Django 5.1.8 on 2025-06-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_alter_contact_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_primary_contact',
            field=models.BooleanField(default=False),
        ),
    ]
