# Generated by Django 5.1.8 on 2025-04-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_task_content_type_remove_task_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(default=None, null=True, upload_to='task_attachments/'),
        ),
    ]
