# Generated by Django 5.1.8 on 2025-05-15 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_remove_accounts_notes_notes'),
        ('activities', '0005_alter_task_assigned_by_and_more'),
        ('leads', '0022_rename_account_leadnotes_lead'),
        ('users', '0012_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('follow_up', 'Follow Up'), ('after_sale', 'After Sale'), ('leads', 'Leads')], max_length=20, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to='users.employee')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='Customer.accounts')),
                ('to_contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='Customer.contact')),
                ('to_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='leads.leads')),
            ],
        ),
    ]
