# Generated by Django 5.1.8 on 2025-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
