# Generated by Django 5.1.8 on 2025-05-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_task_created_by_alter_task_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
