# Generated by Django 5.1.8 on 2025-06-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='end_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.IntegerField(default=None),
        ),
    ]
