# Generated by Django 5.1.8 on 2025-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_remove_meeting_end_time_meeting_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
