# Generated by Django 5.1.8 on 2025-07-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_contact_is_primary_contact'),
        ('activities', '0015_email_recipient_email_email_recipient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.contact'),
        ),
    ]
