# Generated by Django 5.1.4 on 2025-02-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_remove_tenant_owner_tenant_tenant_owner_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
