# Generated by Django 5.1.4 on 2025-02-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant_owner',
        ),
    ]
