# Generated by Django 5.1.8 on 2025-05-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_tenantbilling_billinginvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantbilling',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenantsmtpsettings',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='BillingInvoice',
        ),
        migrations.DeleteModel(
            name='TenantBilling',
        ),
        migrations.DeleteModel(
            name='TenantSMTPSettings',
        ),
    ]
