# Generated by Django 5.1.8 on 2025-05-02 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_remove_tenantbilling_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_name', models.CharField(max_length=200)),
                ('per_user_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('billing_day', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('last_billed_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user_count', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_pdf_url', models.URLField(blank=True, null=True)),
                ('tenant_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenant.tenantbilling')),
            ],
        ),
    ]
