# Generated by Django 5.1.8 on 2025-05-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_tenantbilling_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantbilling',
            name='billing_day',
        ),
        migrations.AddField(
            model_name='tenantbilling',
            name='billing_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
