# Generated by Django 5.1.8 on 2025-05-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_remove_tenantbilling_billing_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbilling',
            name='last_billing_status',
            field=models.BooleanField(default=False),
        ),
    ]
