# Generated by Django 5.1.4 on 2025-01-16 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
