# Generated by Django 5.1.4 on 2025-02-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_rbac', '0001_initial'),
        ('rabc', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='Main_rbac.permission'),
        ),
    ]
