# Generated by Django 5.1.4 on 2025-02-13 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabc', '0005_employee_alter_role_permission_employeerole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rabc.role'),
        ),
    ]
