# Generated by Django 5.1.4 on 2025-02-15 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabc', '0006_alter_role_parent_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rabc.role'),
        ),
        migrations.DeleteModel(
            name='EmployeeRole',
        ),
    ]
