# Generated by Django 5.1.4 on 2025-02-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_rbac', '0002_remove_permission_tenant'),
        ('rabc', '0007_employee_role_delete_employeerole'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code_name', models.CharField(max_length=200)),
                ('module', models.CharField(max_length=100)),
                ('permission', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main_rbac.permission')),
            ],
        ),
    ]
