# Generated by Django 5.1.4 on 2025-02-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabc', '0009_roleacesspermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission',
        ),
    ]
