# Generated by Django 5.1.4 on 2025-02-20 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabc', '0010_remove_role_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
