# Generated by Django 5.1.4 on 2025-02-20 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabc', '0011_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleacesspermission',
            name='Permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenantpermission', to='rabc.tenantpermission'),
        ),
    ]
