# Generated by Django 5.1.4 on 2025-02-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='tenant',
        ),
    ]
